name: update-catalog

on:
  schedule:
    - cron: '0 2 * * */2'

jobs:
  new_content:
    runs-on: ubuntu-latest
    steps:
      - name: Add new content to catalog
        run: |
          curl --request GET \
          --url "https://streamorskip.com/api/cron/addToCatalog" \
          --header "apikey: ${{ process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}, Authorization: Bearer ${{ process.env.SUPABASE_KEY }}"
      - name: Add ratings
        run: |
          curl --request GET \
          --url "https://streamorskip.com/api/cron/rating" \
          --header "apikey: ${{ process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}, Authorization: Bearer ${{ process.env.SUPABASE_KEY }}"
      - name: Add genres
        run: |
          curl --request GET \
          --url "https://streamorskip.com/api/cron/genre" \
          --header "apikey: ${{ process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}, Authorization: Bearer ${{ process.env.SUPABASE_KEY }}"
      - name: Add trailers
        run: |
          curl --request GET \
          --url "https://streamorskip.com/api/cron/trailer" \
          --header "apikey: ${{ process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}, Authorization: Bearer ${{ process.env.SUPABASE_KEY }}"