name: update-catalog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * */2'


jobs:
  new_content:
    runs-on: ubuntu-latest
    steps:
      - name: Add new content to catalog
        run: |
          curl --request GET \
          --url "https://api.streamorskip.com/api/cron/addToCatalog" \
          --header "WORKER-KEY: ${{ secrets.WORKER_KEY }}"
      - name: Add ratings
        run: |
          curl --request GET \
          --url "https://api.streamorskip.com/api/cron/rating" \
          --header "WORKER-KEY: ${{ secrets.WORKER_KEY }}"
      - name: Add genres
        run: |
          curl --request GET \
          --url "https://api.streamorskip.com/api/cron/genre" \
          --header "WORKER-KEY: ${{ secrets.WORKER_KEY }}"
      - name: Add trailers
        run: |
          curl --request GET \
          --url "https://api.streamorskip.com/api/cron/removeFromCatalog" \
          --header "WORKER-KEY: ${{ secrets.WORKER_KEY }}"
      - name: Check for deleted content
        run: |
          curl --request GET \
          --url "https://api.streamorskip.com/api/cron/removeFromCatalog" \
          --header "WORKER-KEY: ${{ secrets.WORKER_KEY }}"
